spring:
  datasource:
    username: ShopSumProject
    password: ShopSumProject
    url: jdbc:mysql://localhost:3306/ShopSumProject
    
  jpa:
    hibernate:
      ddl-auto: update   
    show-sql: true
    